### ISSUE TITLE
Ne fonctionne pas chez moi

### ISSUE THREAD

**Issue by aclarembeau** [cnp3/Linksimulator#1]
Bonjour, 

Quand je lance le programme avec la commande `./link_sim -p 1234 -P 4567` puis que je fais dans deux terminaux `./receiver :: 4567 -f out.txt` et `./client ::1 1234 -f in.txt`, le recepteur ne recoit aucun message du client, pourtant, cela fonctionne sans le simulateur de liens. 
De plus, ma gestion des socket est censée être correcte car elle fonctionnait sur la tâche inginious.

Je vous envoie en pièce jointe une photo (accompagnée de tcpdump). 
Aurais-je mal compris l'utilisation des arguments du programme? 
![espace de travail 1_132](https://cloud.githubusercontent.com/assets/10834626/10538026/02f2baea-73f6-11e5-9add-beb0574481f5.png)

(J'ai mis un debug sur STDOUT qui prouve que le client envoie, qu'il ne reçoit pas de Ack puis le timer expire puis le client retransmet les paquets puis il ne reçoit pas de ack et ainsi de suite)

Merci d'avance

**Comment by oliviertilmans** [comment]
La trace tcpdump montre que vous envoyez des paquets IPv4 et non IPv6 (IP et non IP6).
Le proxy ne les accepte pas de façon explicite:
https://github.com/oliviertilmans/LINGI1341-linksim/blob/master/link_sim.c#L335
https://github.com/oliviertilmans/LINGI1341-linksim/blob/master/link_sim.c#L344

La conséquence est que l'OS répond de manière attendue: ICMP port unreachable, puisque aucun programme n'écoute sur (127.0.0.1; 1234 ) , link_sim écoutant sur ( ::1; 1234 ), le paquet n'est donc jamais relayé.

**Comment by aclarembeau** [comment]
Merci beaucoup :)
